CUR_ID_MAP = {
    1: "FK WALLET RUB",
    2: "FK WALLET USD",
    3: "FK WALLET EUR",
    4: "VISA RUB",
    6: "Yoomoney",
    7: "VISA UAH",
    8: "MasterCard RUB",
    9: "MasterCard UAH",
    10: "Qiwi",
    11: "VISA EUR",
    12: "МИР",
    13: "Онлайн банк",
    14: "USDT (ERC20)",
    15: "USDT (TRC20)",
    16: "Bitcoin Cash",
    17: "BNB",
    18: "DASH",
    19: "Dogecoin",
    20: "ZCash",
    21: "Monero",
    22: "Waves",
    23: "Ripple",
    24: "Bitcoin",
    25: "Litecoin",
    26: "Ethereum",
    27: "SteamPay",
    28: "Мегафон",
    32: "VISA USD",
    33: "Perfect Money USD",
    34: "Shiba Inu",
    35: "QIWI API",
    36: "Card RUB API",
    37: "Google pay",
    38: "Apple pay",
    39: "Tron",
    40: "Webmoney WMZ",
    41: "VISA / MasterCard KZT",
    42: "СБП",
    44: "СБП (API)",
}
